<a href="https://colab.research.google.com/github/JS0501/ESAA_YB3/blob/main/ESAA_YB_WEEK1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print('numpy version:', np.__version__)
np.show_config()

numpy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
array1 = np.array([1,2,3])
memory_size = array1.nbytes
print("memory size of array1:", array1.nbytes, "bytes")

memory size of array1: 24 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
vector1 = np.arange(10,50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
vector1 = np.arange(10,50)
reverse_vector1 = vector1[::-1]
print(reverse_vector1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
matrix1 = np.arange(9).reshape(3,3)
print(matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
array2 = np.array([1,2,0,0,4,0])
indices = np.nonzero(array2)
print(indices)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [15]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [16]:
array3 = np.random.rand(3,3,3)
print(array3)

[[[0.49231295 0.79697818 0.80846694]
  [0.76756843 0.60873767 0.49738121]
  [0.25723136 0.53077778 0.24571286]]

 [[0.39265034 0.06061406 0.47857164]
  [0.67186841 0.45553645 0.91009831]
  [0.01451801 0.07170355 0.00200353]]

 [[0.64575233 0.95471841 0.94410224]
  [0.13036072 0.51036247 0.16379445]
  [0.54279044 0.30491831 0.72838833]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [17]:
array4 = np.random.rand(10,10)
min_value = np.min(array4)
max_value = np.max(array4)
print(array4)
print(min_value)
print(max_value)

[[0.82844712 0.87876811 0.48189747 0.77410477 0.51883833 0.19900849
  0.15373453 0.58159745 0.36827497 0.29287731]
 [0.0253606  0.21595675 0.42665914 0.35435732 0.74936439 0.61306771
  0.05780623 0.04187864 0.17630666 0.74176605]
 [0.56935538 0.76799839 0.44480462 0.02830432 0.28690559 0.9772928
  0.89199348 0.55156805 0.00358485 0.14853826]
 [0.67342704 0.15003344 0.98881869 0.7993918  0.54356685 0.65562067
  0.79147699 0.99374206 0.98151037 0.577083  ]
 [0.57608488 0.52482644 0.06890753 0.85936128 0.81436852 0.10624438
  0.15689132 0.22853943 0.82212989 0.58152496]
 [0.93122848 0.89079291 0.20086591 0.83141524 0.95535131 0.77976938
  0.80892661 0.02018755 0.90389123 0.58323198]
 [0.3185589  0.57732119 0.75587711 0.24352624 0.36604535 0.56355792
  0.47058798 0.43252185 0.85266905 0.60520157]
 [0.97490903 0.38009905 0.69527543 0.51703064 0.38645546 0.2573683
  0.10094415 0.63144284 0.13687747 0.60088402]
 [0.16164488 0.89911766 0.46135429 0.21167593 0.29687321 0.36289062
  0.85746837 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [18]:
vector2 = np.random.rand(30)
mean_value = np.mean(vector2)
print(vector2)
print(mean_value)

[0.92780251 0.80327547 0.21850323 0.08527353 0.78747663 0.01749741
 0.18832053 0.24672724 0.58868975 0.75790273 0.43411726 0.09716177
 0.0632663  0.47624034 0.4309899  0.08787647 0.39978913 0.18762202
 0.1179221  0.35706569 0.3709385  0.1850171  0.55689453 0.94531188
 0.13302925 0.58614421 0.12774941 0.14296894 0.38587039 0.01237479]
0.3573273000592137


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [20]:
array5 = np.zeros((4,4))
array5[0,:] = 1
array5[-1,:] = 1
array5[:,0] = 1
array5[:,-1] = 1
print(array5)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

result: nan, False, False, nan, True, False

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [28]:
matrix2 = np.zeros((5,5))
matrix2[np.arange(1,5), np.arange(0,4)] = [1,2,3,4]
print(matrix2)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [31]:
matrix3 = np.zeros((8,8))
matrix3[1::2,::2] = 1
matrix3[::2,1::2] = 1
print(matrix3)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [32]:
index = np.unravel_index(100,(6,7,8))
print(index)

(1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [33]:
x = np.random.rand(5,5)
xbar = np.mean(x)
s = np.std(x)
z = (x-xbar)/s
print("Normalized 5x5 random matrix:\n",z)

Normalized 5x5 random matrix:
 [[-0.74052183  1.04713732 -0.44662996  0.39773805  1.01219321]
 [-1.31623531  0.04174139  0.65986106  1.24899876 -0.44145962]
 [ 1.10445387  0.44778902  1.23107965 -1.30082931 -1.52450025]
 [ 1.12176495 -0.96070527 -1.39460119 -0.17866702 -1.21057274]
 [ 0.69733554  1.21069904 -0.35762908  1.11650636 -1.46494665]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [34]:
color_dtype = np.dtype([('R', np.ubyte),('G',np.ubyte),('B',np.ubyte),('A',np.ubyte)])
print(color_dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
